export default Object.freeze({
    DEFAULT_FIXED_WIDTH: 48,
    DEFAULT_MINIMUM_WIDTH: 100,
    LINE_ACTIONS_WIDTH: 48,
    LINE_COUNTER_WIDTH: 60,
    LINE_CHECKBOX_WIDTH: 32,
    LINE_CHECKBOX_BUTTON_WIDTH: 64,
});
